# Generated by Django 4.0.4 on 2022-07-25 14:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refUsers', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('tasks', models.JSONField(blank=True)),
            ],
        ),
    ]
