# Generated by Django 4.0.4 on 2022-07-21 12:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profiluser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refUsers', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('clients', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
